### ISSUE TITLE
Conditionally Keep Menu Open 

### ISSUE THREAD

**Issue by hiddenroadss** [Confidenceman02/elm-select#191]
I am using this library for implementing multi-select filters in a project. Currently, every time a user selects an option, the menu closes, which triggers a request to the backend with updated filters. Often, users select more than one filter option which leads to multiple redundant backend calls, potentially affecting performance and user experience.

 It would be beneficial to have an enhancement where the `keepMenuOpen` parameter can be used, but with additional configuration to close the select dropdown under specific conditions, such as clicking the chevron icon only.

**Comment by Confidenceman02** [comment]
Hello hello!

Thanks for opening the issue.

Let's see if we can work around the issue with what we already have.

I'm assuming you are sending requests on the `SelectBatch` action.

If you haven't already you can try send requests on the `Blur` action.

How this would work is you use `SelectBatch` to collect all the options that are being selected, then when you see the `Blur` action you can fire off the request with the collected options.

`Blur` should fire when someone clicks away from the select. 

## Some things to consider

`Blur` is not perfect, from memory it can be a little chatty depending on what is clicked, but I'm pretty confident it will do what you need it to.

In regards to keeping the menu open and then customizing when it closes, I would have to think about whether that would be a good feature or not. Elm-select is very optimized for filter searching so selecting multiple items via search and pressing enter does go a long way, but I do understand that using a mouse to click a bunch of items would also be pretty convenient.

Let me know if that helps!

**Comment by Confidenceman02** [comment]
> I checked native multiselect and it won't be suitable for my usecases, patially because native select doesn't allow you to pick what you want, you need to pick ranges + these filters use your virtual scroll feature)

Yea the native elements won't really give you any extra functionality around this. 

> Blur event partially solve the issue, but the problem is it isn't intuitive and might be hard to understand why you are picking something but state is not changing.

That's fair.

> That is why I liked select variant which keeps menu open, because it is clear that you are picking options and only when you finish - something will happen.

I see what you are asking for, I'll have a look and see how feasible this is to do without changing a bunch of things because it seems like a very specific use case. If it can be done smoothly then I'm happy to give it a shot.

I'll let you know what I find next week!

**Comment by Confidenceman02** [comment]
Having thought about this, it might be possible to achieve what you want by possibly just exposing 1 extra `Action`, the `CloseMenu` action.

You could use this in conjunction with the `keepMenuOpen` config option. 

The way I'm thinking about it is `CloseMenu` only dispatches when the user tries to actively close the menu, not as a side effect of selecting something. That way when you see the action you can be confident the user want's to actually close the menu. Also, you can confidently send off your request on this action with the selected items. 

Things like `Esc`, or clicking the chevron button would trigger this.

I'll play with this and see if I can get a working example for you.

**Comment by hiddenroadss** [comment]
> I'll play with this and see if I can get a working example for you.
You're helping me a lot, thank you)

**Comment by Confidenceman02** [comment]
I have an example on this [branch](https://github.com/Confidenceman02/elm-select/tree/close-menu-action) in the examples directory under the name `KeepMenuOpen`

Are you able to go into examples directory and run:

```
elm reactor
```

And just have a play with the example. 

I'm pretty sure it does what you need it to.

**Comment by hiddenroadss** [comment]
Hello!
I finished my previous taks, finally, and checked your branch)
It does work the way I need in general. 
But for some reason now when I click on dropdown chevron - it doesn't emit Focus action. I've reviewed your last 3 commits (I believe that's it, right?) and can't find what code could break it.

`(StyledAttribs.css indicatorContainerStyles
            :: withMsg
  )`
  I thought about this part, because it can stop events propagation, but when I remove `withMsg` - it still doesn't work

**Comment by Confidenceman02** [comment]
> But for some reason now when I click on dropdown chevron - it doesn't emit Focus action. 

The action `MenuClose` is actually super misleading, it fires when the menu is toggled, so it might open or close the menu.
Maybe a better name is `MenuToggle`.

But yes you're right, it's not focusing the input when you click it initially and that's why the `Focus` action isn't firing! 
I'll jump in there this weekend and sort that out.

**Comment by Confidenceman02** [comment]
@hiddenroadss Ok pull and give it another shot. Focus even should be firing now.

**Comment by hiddenroadss** [comment]
@Confidenceman02 , hello)
Yes, it is firing, the only issue left is that if I deselect one or clear all selected and try to close the menu clicking on chevron - it doesn't do anything
although it works if I just click outside the select

**Comment by hiddenroadss** [comment]
It makes sense, because it wasn't in your example:D
I forgot I added it, because we have similar situation when user deselect items one by one. I want to fire request only when they finish, so when user click on deselect one, I open menu. then when he/she is done - they can close the menu or just blur out of filter

**Comment by Confidenceman02** [comment]
Hello hello!

Thanks for checking it out. 

> Yes, it is firing, the only issue left is that if I deselect one selected(not clear all) and try to close the menu clicking on chevron - it doesn't do anything.

Ah yes, I wasn't dispatching the close action for that particular case.

Ok added it. I think that should do it. 

Please give it another shot and if it does what you need I am going to write a bunch of tests as it adds a bit of complexity, then I'll do a release.

**Comment by hiddenroadss** [comment]
![image](https://github.com/user-attachments/assets/391a4c5d-e9a5-431a-8c38-35313ce9838b)
It didn't help, and I believe it is because of how Deselect and keepOpen works together.
So on this screen I clicked on selected item to deselect it.
So as I understand it, it focuses select, removes this one item, but then `keepMenuOpen` Focus it ones more, which looks like a bug here. What do you think?
And then 9 Nothing actions are me clicking on chevron to close this menu

`Just (Select.Deselect deletedItems) ->
            ( List.filter (\i -> not (List.member i deletedItems)) xs, state |> Select.keepMenuOpen True )
`

**Comment by Confidenceman02** [comment]
I'm not sure if we have it set up the same. 

But for me the menu closes fine. 

https://www.loom.com/share/845ed195fe714202b7a15da0de6891ac?sid=8b743e3f-53ad-4ac3-b163-90ef6f0a3962

Are you modifying the example by any chance?

**Comment by hiddenroadss** [comment]
the only difference we have in example code is that I'm opening menu when user deselect item and the menu is closed. Although deselecting doesn't trigger Blur event, it still should be obvious that we are not doing anything yet. So when user clicks to deselect - I open menu. Then, they can deselect how many items they want and click on chevron or just outside to trigger action
And now with this 
```
( updatedSelectedItems, st ) =
                    case maybeAction of
                        Just (Select.Select i) ->
                            ( model.selectedItems ++ [ i ], selectState |> Select.keepMenuOpen True )

                        Just (Select.Deselect deletedItems) ->
                            ( List.filter (\i -> not (List.member i deletedItems)) model.selectedItems, selectState |> Select.keepMenuOpen True )

```
keepMenuOpen it doesn't work with chevron.

**Comment by Confidenceman02** [comment]
Could you please make a branch with your code so I can jump in there and have a look please?

It's a bit difficult to debug via text.

Thanks!

**Comment by hiddenroadss** [comment]
sure)
https://github.com/hiddenroadss/elm-select/tree/close-menu-action-with-deselect

**Comment by Confidenceman02** [comment]
Hey there,

I checked out your branch `close-menu-action-with-deselect`.

This branch didn't have the latest changes I made from our conversation above which is why it wasn't working. 

I rebased with `close-menu-action` branch and works perfectly. Unless there is something I'm missing?

This is a loom from your repo `close-menu-action-with-deselect` branch after rebase.

https://www.loom.com/share/63e9221f3d9f455ab1dd8dbe2a52656d?sid=ba701741-3a5d-41cd-b6a4-5b79362599a9

**Comment by hiddenroadss** [comment]
Wow, that's weird, I thought I added new changed
everything is working great:)

**Comment by Confidenceman02** [comment]
> Wow, that's weird, I thought I added new changed everything is working great:)

Ha! I do that all the time, all good!

Ok I'm going to write some UI tests and make sure it's not breaking anything then I'll make a release.

**Comment by Confidenceman02** [comment]
Released in [12.0.0](https://package.elm-lang.org/packages/Confidenceman02/elm-select/12.0.0)

**Comment by Confidenceman02** [comment]
Thanks so much for testing it with your requirements and being patient! :)

Are you happy to close this issue?

**Comment by hiddenroadss** [comment]
> Thanks so much for testing it with your requirements and being patient! :) 
I thought that's me who should thank you, but I'm glad you also liked it )

> Are you happy to close this issue?
Small related question - is there a way to `blur` programmatically select? Why do I need it - right now we have 2 options how select can be closed (adn some api calls triggered) : 
1. MenuClose
2.Blur
and MenuClose doesn't blur the input, so I can smell some potential bugs here))
so if I could make it run requests on one action instead - it would be less error-prone, I believe

**Comment by Confidenceman02** [comment]
> Small related question - is there a way to blur programmatically select? Why do I need it - right now we have 2 options how select can be closed (adn some api calls triggered)

`Elm/select` wont do this for you but you can use the elm/browser [blur](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Dom#blur) function to blur any element you want. You would just need to pass it the select id.

If you're going to do this I would recommend using [staticSelectIdentifier](https://package.elm-lang.org/packages/Confidenceman02/elm-select/latest/Select#staticSelectIdentifier) for producing static id's.

**Comment by hiddenroadss** [comment]
Thanks!
then I believe we can close this issue :)
