### ISSUE TITLE
Minimum control height styling

### ISSUE THREAD

**Issue by rague** [Confidenceman02/elm-select#196]
We can currently set a minimum height. However this minimum achievable size is already tall due to the arrow's "padding" css attribute being set to 8px. It could be great if we can change this.

**Comment by Confidenceman02** [comment]
Hi Rague!

Thanks for opening an issue.

I think customizing the dropdown indicators padding makes good sense. 

I'll have a look at this this weekend for you.

Many thanks!

**Comment by Confidenceman02** [comment]
It looks like the dropdown indicator lives inside an `indicatorContainer`, and this is where the padding is being applied. 

So changing the padding of any indicator will affect all other's which will make them consistent.

**Comment by Confidenceman02** [comment]
Released in [12.1.0](https://package.elm-lang.org/packages/Confidenceman02/elm-select/12.1.0/)

**Comment by Confidenceman02** [comment]
Let me know if this works for you @rague . If it does feel free to close the issue.

Thanks again!

**Comment by rague** [comment]
Perfect, thank you for your responsiveness !
