### ISSUE TITLE
Change Missing Dep

### ISSUE THREAD

**Issue by jaredramirez** [Confidenceman02/elm-select#26]
Hey there, thanks for the great package!

It seems that one of this packages deps, `matken11235/html-styled-extra`, no longer exists (this user's github has been deleted I think). This package now fails to build. It looks like someone has already forked it [ken-matsui/html-styled-extra](https://package.elm-lang.org/packages/ken-matsui/html-styled-extra/latest/). Can you update this dep and republish?

**Comment by Confidenceman02** [comment]
Thanks for calling this out! 

New version published so should be good to go!
