### ISSUE TITLE
Clearing a select submits a form that have `onSubmit` event

### ISSUE THREAD

**Issue by ringvold** [Confidenceman02/elm-select#55]
Hi!

I'm trying out the package for in project and I have a issue with clearable selects.
I have the select inside a form with a `onSubmit` listener and when I have a select with `clearable True` and try to clear the field it also submits the form. I use `Select.single` and not `Select.singleNative` (for now).

I looked at the code for clearing and it seems that the event handler uses `stopPropagation = True` and `preventDefault = True` so based on that I would expect the form to not be submitted.

Do you have any thoughts? Am I doing it wrong?

**Comment by Confidenceman02** [comment]
Hi there! 

Thanks for submitting the issue.

I don't think you are doing anything wrong at all 👍 

Having a quick look at the code it looks like I didn't set a `type` attribute on the button, so it defaults to a submit.

Setting `type "button"` I think will do the trick!

I'll patch this later today! 😄

**Comment by Confidenceman02** [comment]
Any chance you can create an ellie app example that recreates this? I actually can't recreate it on chrome, firefox or safari.
Even if you add your code in a comment that would be helpful.

Clearing doesn't submit the form for me.

**Comment by Confidenceman02** [comment]
Ah I get it now! It's when you press enter specifically. Mouse clicking doesn't seem to submit it.

**Comment by Confidenceman02** [comment]
fixed in https://github.com/Confidenceman02/elm-select/pull/58

**Comment by Confidenceman02** [comment]
released [3.2.2](https://package.elm-lang.org/packages/Confidenceman02/elm-select/latest/)
