### ISSUE TITLE
Listbox z-index edge case when using 2 elm-selects

### ISSUE THREAD

**Issue by klufkin** [Confidenceman02/elm-select#67]
Hello! First off, I just want to say that I really appreciate the time and effort that went into developing this component! I'm a big fan of its usability.

I noticed while trying it out that when you have one elm-select's listbox displaying over another elm-select you can see multiSelectTag close buttons through the overlapping listbox. See screenshot for reference.

<img width="548" alt="Screen Shot 2022-05-30 at 1 34 58 PM" src="https://user-images.githubusercontent.com/6633869/171040141-ba615cdf-b421-4c6f-b733-ee7d31d8de1f.png">

It looks like bumping up the listbox's z-index to 2 fixes this issue. 
https://github.com/Confidenceman02/elm-select/blob/d9520a3f38a6c4e4f884170b6d7963cd7a754c0c/src/Select.elm#L1760

Currently I'm fixing this by overriding the css. If you'd like, I'd be happy to create a PR. Thanks again!

**Comment by Confidenceman02** [comment]
Hi Kevin!

Many thanks for opening an issue and the kind words! 

Yes absolutely, please feel free to open a PR. Otherwise, I can get to this this weekend if you can wait.

👋

**Comment by Confidenceman02** [comment]
Fixed in release [4.1.1](https://github.com/Confidenceman02/elm-select/releases/tag/4.1.1)
